# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0007_auto_20170731_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='num_of_retries',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number of retries'),
        ),
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'sent'), (1, 'failed'), (2, 'queued'), (3, 'retry')], db_index=True, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'sent'), (1, 'failed'), (3, 'retry')], verbose_name='Status'),
        ),
    ]
